using System;
using AutoPoco.Engine;

namespace Datasources
{
    public class CitySource  : DatasourceBase<String>
    {
        private readonly Random _random = new Random(1337);

        public override string Next(IGenerationContext context)
        {
            return Cities[_random.Next(0, Cities.Length)];
        }

        private static readonly string[] Cities = new[]{
            "Kearns",
            "Rolla",
            "Kalamazoo",
            "Orem",
            "Columbia",
            "Oakland",
            "Valencia",
            "Farmington",
            "Detroit",
            "Pine Bluff",
            "Seward",
            "Visalia",
            "Waycross",
            "Irving",
            "Kona",
            "Malibu",
            "Fremont",
            "Paterson",
            "Geneva",
            "Kenosha",
            "Moultrie",
            "Cleveland",
            "Farmington",
            "Johnson City",
            "Muskegon",
            "Brea",
            "Palm Springs",
            "Hazleton",
            "Frankfort",
            "Merced",
            "Goose Creek",
            "Riverton",
            "Fremont",
            "Salinas",
            "Isle of Palms",
            "Littleton",
            "Johnson City",
            "Glendora",
            "San Juan",
            "Opelousas",
            "Astoria",
            "New London",
            "Murray",
            "Woodward",
            "Asheville",
            "Baltimore",
            "Los Alamitos",
            "Great Falls",
            "Redding",
            "Sitka",
            "Sandpoint",
            "Gatlinburg",
            "Anaconda",
            "Birmingham",
            "Rolla",
            "New Iberia",
            "Coral Springs",
            "Juneau",
            "Youngstown",
            "Logan",
            "Worland",
            "Glendora",
            "Edina",
            "Fort Collins",
            "Buena Park",
            "Palos Verdes Estates",
            "Santa Barbara",
            "Mentor",
            "Allentown",
            "Muskegon",
            "Cumberland",
            "Bandon",
            "Daly City",
            "Santa Cruz",
            "Athens",
            "East Lansing",
            "Stafford",
            "Mentor",
            "Nanticoke",
            "Myrtle Beach",
            "Hoboken",
            "Houston",
            "Vincennes",
            "Idaho Springs",
            "Lawton",
            "Pendleton",
            "Apple Valley",
            "Paterson",
            "Calumet City",
            "Anchorage",
            "Concord",
            "Brownsville",
            "Guthrie",
            "Kettering",
            "Isle of Palms",
            "Lancaster",
            "Camden",
            "Deadwood",
            "Appleton",
            "Cedar Rapids"
        };
    }           
}